version: "3"
volumes:
  headway_graphhopper_vol:
    external: true
services:
  mbtileserver:
    image: maptiler/tileserver-gl
    environment:
      PORT: 8000
    env_file: .env
    command: '/data/${HEADWAY_AREA}.mbtiles -p 80'
    volumes:
      - "./data/:/data/:ro"
  photon:
    image: headway_photon
    build: ./geocoder/photon
    env_file: .env
    volumes:
    - "./data/${HEADWAY_AREA}.photon/photon_data:/photon/photon_data"
  nominatim:
    image: mediagis/nominatim:4.0
    environment:
      PBF_PATH: /data/${HEADWAY_AREA}.osm.pbf
    env_file: .env
    volumes:
      - "./data/:/data/:ro"
      - "./data/nominatim_pg/:/var/lib/postgresql/12/main"
      - "./data/nominatim_flatnode/:/nominatim/flatnode"
  graphhopper:
    image: headway_graphhopper
    build: ./graphhopper
    env_file: .env
    volumes:
    - "headway_graphhopper_vol:/graph_volume"
  nginx:
    image: headway_nginx
    build: ./web
    env_file: .env
    environment:
      HEADWAY_RESOLVER: 127.0.0.11
      HEADWAY_GRAPHHOPPER_URL: http://graphhopper:8989
      HEADWAY_NOMINATIM_URL: http://nominatim:8080
      HEADWAY_PHOTON_URL: http://photon:2322
      HEADWAY_TILESERVER_URL: http://mbtileserver:8000
    ports:
    - "8080:8080"
