version: "3"
services:
  mbtileserver:
    image: headway_tileserver
    environment:
      PORT: 7777
      TILE_DIR: "/tiles"
      VERBOSE: "true"
    ports:
      - "8081:7777"
  photon:
    image: headway_photon
  valhalla:
    image: headway_valhalla_run
    ports:
      - "8002:8002"
    environment:
      use_tiles_ignore_pbf: "True"
