version: "3"
services:
  mbtileserver:
    image: headway_tileserver
    environment:
      PORT: 8000
  photon:
    image: headway_photon
  valhalla:
    image: headway_valhalla_run
    environment:
      use_tiles_ignore_pbf: "True"
  nginx:
    image: headway_nginx
    ports:
    - "${NGINX_PORT}:${NGINX_PORT}"
