version: "3"
services:
  mbtileserver:
    image: headway_tileserver
    environment:
      PORT: 8000
      TILE_DIR: "/tiles"
      ROOT_URL: "/tiles"
    ports:
    - "8000:8000"
  photon:
    image: headway_photon
  valhalla:
    image: headway_valhalla_run
    environment:
      use_tiles_ignore_pbf: "True"
  nginx:
    image: headway_nginx
    ports:
    - "8080:8080"