services:
  mbtileserver:
    environment:
      PORT: 7777
      TILE_DIR: "/mbtiles"
      VERBOSE: true
    entrypoint: mbtileserver
    ports:
      - "8081:7777"
  photon:
    image: headway_photon