services:
  mbtileserver:
    image: headway_tileserver
    environment:
      PORT: 7777
      TILE_DIR: "/tiles"
      VERBOSE: "true"
    ports:
      - "8081:7777"
  photon:
    image: headway_photon